include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  exclude:
    - build/**
    - "**/*.g.dart"
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    omit_local_variable_types: false
    one_member_abstracts: false
